apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  selector:
    {{- include "app2.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
